package commands

import (
	"github.com/Notwinner0/gvcs/internal/objects"
	"github.com/Notwinner0/gvcs/internal/refs"
	"github.com/Notwinner0/gvcs/internal/repo"
)

func CmdTag(name, object string, annotated bool) error {
	gitRepo, err := repo.RepoFind(".", true)
	if err != nil {
		return err
	}

	if name != "" {
		return tagCreate(gitRepo, name, object, annotated)
	}

	// List tags
	refList, err := refs.RefList(gitRepo, repo.RepoPath(gitRepo, "refs", "tags"))
	if err != nil {
		return err
	}
	refs.ShowRef(refList, "tags", false)
	return nil
}

func tagCreate(gitRepo *repo.GitRepository, name, ref string, createTagObject bool) error {
	sha, err := objects.ObjectFind(gitRepo, ref, "", true)
	if err != nil {
		return err
	}

	if createTagObject {
		// Create tag object
		tag := &objects.GitTag{
			Kvlm: make(map[string][]string),
		}
		tag.Kvlm["object"] = []string{sha}
		tag.Kvlm["type"] = []string{"commit"} // Assuming we're tagging commits
		tag.Kvlm["tag"] = []string{name}
		// In a real implementation, you'd get the user's name from config
		tag.Kvlm["tagger"] = []string{"gvcs <gvcs@example.com>"}
		tag.Message = "A tag generated by gvcs!\n"

		tagSHA, err := objects.ObjectWrite(tag, gitRepo)
		if err != nil {
			return err
		}
		// Create reference to the tag object
		return refs.RefCreate(gitRepo, "refs/tags/"+name, tagSHA)
	}

	// Create lightweight tag (just a ref)
	return refs.RefCreate(gitRepo, "refs/tags/"+name, sha)
}
